#' Align analyses with humdrum data.
#'
#' This function takes one or more harmonic analyses
#' (output by \code{\link{filterAnalyses}}) and aligns them with the appropriate humdrum
#' data.
#' @param analyses A list of analyses output by \code{\link{filterAnalyses}}. Each vector
#' of chord symbols should be the same length as the \code{nrow{\link{ChoraleTable_Slices}}}.
#'
#' @return A list of character veators, with each element of each vector
#' being corresponding to a single row/slice in the \code{\link{ChoraleTable_Slices}} object.
#' @export
generateHumdrum <- function(analyses) {
  names(analyses) <- LETTERS[((seq_along(analyses) - 1) %% 26) + 1]

  ChoraleTable_Slices <- cbind(ChoraleTable_Slices, as.data.table(analyses))
  ChoraleTable_Slices[ ,
                       { filename <- unique(Slice_FileName)
                         func <- getandprepHumdrum(filename)
                         anals <- lapply(names(analyses), get, envir = environment())
                         list(Records = func(anals),
                              FileName = filename)},
                       by = Slice_FileNumber]


}

getandprepHumdrum <- function(filename) {
 filename <- system.file('extdata',
                         filename,
                         package = 'FlexibleChoraleHarmonicAnalysis')
 records <- readLines(filename)

 global       <- grepl('^!!', records)
 data         <- grepl('^[^!=*]', records) & grepl('[^r]', gsub('[^A-Ga-gr]*', '', records))
 localnondata <- !data & !global

 firstspine <- gsub('\t.*', '' , records)

 # create the interpretations, barlines, and comments for the new analysis spines
 newSpine <- rep('.', length(records))
 newSpine[global] <- ''

 newSpine[global] <- records[global]
 newSpine[localnondata] <- substr(firstspine[localnondata], start = 1L, stop = 1L)

 globalInterp <- grepl('^\\*\\*', firstspine)
 newSpine[globalInterp] <- gsub('\\*\\*.*', '**chordsymbol', firstspine[globalInterp])

 tandemInterps <- grepl('^\\*[A-Ga-g][#-]*:', firstspine) |
                  grepl('^\\*M[1-9][1-9]*/[1-9][0-9]*', firstspine) |
                  grepl('^\\*met\\(.\\)', firstspine) |
                  grepl('^\\*>', firstspine) |
                  grepl('^\\*-', firstspine) |
                  grepl('^=', firstspine) |
                  grepl('^\\*MM[1-9][0-9]*', firstspine) |
                  grepl('^!..*ian$', firstspine)


 newSpine[tandemInterps] <- firstspine[tandemInterps]

 function(analyses) {
  if (any(lengths(analyses) != sum(data))) stop(paste("Analysis isn't right length for file", filename))

  newSpines <- lapply(analyses,
                      function(anal) {
                        newSpine[data] <- anal
                        newSpine
                      })

  newSpines <- do.call('paste', c(newSpines, sep = '\t'))




  records[!global] <- paste(records[!global], newSpines[!global], sep = '\t')

  paste(records, collapse = '\n')

 }


}


#############

#' Write annotated humdrum data to files
#'
#' This function writes new humdrum data (original **kern with added harmonic
#' analyses), to text files. The original krn file names are used, with the addition of
#' the word "annotated," a optional label specified by the user, and a different extension (\code{.hum}).
#'
#' @param fileTable A data table representing annotated humdrum files
#'  (output by \code{\link{generateHudrum}}).
#' @param label A character string to append to each filename.
#' Defaults to NULL. Use this to differentiate different batches
#' of analyses you generate.
#'
#' @return NULL
#' @export
writeHumdrum <- function(fileTable, path = './', label = NULL) {
  fileTable$FileName <- gsub('inst/extdata', '', fileTable$FileName)

  if (!is.null(label) && label != '') fileTable$FileName <- gsub('\\.krn$', paste('_', label, '.krn', sep = ''), fileTable$FileName)

  if (is.null(path) || path == '') path <- './'
  if (stringr::str_sub(path, -1, -1) != '/') path <- paste(path, '/', sep = '')
  fileTable$FileName <- paste(path, fileTable$FileName, sep = '')

  fileTable[ ,
             {Records <- paste(Records,
                              '!!! **chordsymbol annotations generated by the FlexibleChoraleHarmonicAnalysis package.',
                              '!!! Condit-Schultz, Ju, and Fujinaga, ISMIR (2018)',
                              paste('!!! Created on', date()), sep = '\n')
             writeLines(Records, con = FileName)},
             by = 1:nrow(fileTable)]

  invisible(fileTable)
}


#' Send a humdrum file to the Verovio Humdrum Viewer
#'
#' This function sends an annotated humdrum data file (generated by
#' \code{\link{generateHumdrum}}) to the \href{https://verovio.humdrum.org/}{Verovio Humdrum Viewer}.
#'
#' @param analyses A list of analyses.
#' @param composer A character string: either "Bach" or "Praetorius" (inexact matches are allowed).
#' @param number An integer in the range 1--371 (for Bach) or 1--200 (for Praetorious).
#'
#' @return NULL
#'
#' @export
showHumdrum <- function(analyses = list(), composer = 'Bach', number = 1) {
  filename



}

